name: CD Example Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: CD Example Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH Connect
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "Berhasil Connect ke server"
             if[ -d "/home/qadriaditya0"]; then
               echo "Ada folder qadriaditya0"
               cd /home/qadriaditya0
               echo "berhasil masuk ke folder qadriaditya0"
             else
               echo "Tidak ada folder qadriaditya0, membuat folder..."
               sudo mkdir /home/qadriaditya0
             fi
