name: CD Example Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: CD Example Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH Connect
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "Berhasil Connect ke Server"
            if [ -d "/home/qadriaditya0" ]; then
              echo "Folder /home/qadriaditya0 ditemukan"
              cd /home/qadriaditya0
              echo "Berhasil Masuk ke Folder"
            else
              echo "Folder /home/qadriaditya0 tidak ditemukan, membuat folder..."
              sudo mkdir /home/qadriaditya0
              echo "Berhasil Masuk ke Folder"
              cd /home/qadriaditya0
            fi